schema_version = "1.0.0"

id = "polychase"
version = "0.0.7"
name = "Polychase"
tagline = "Mesh Based Motion Tracking in Blender"
maintainer = "Ahmed Essam"
type = "add-on"
website = "https://github.com/theartful/polychase"
tags = ["Animation", "Tracking"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
platforms = ["windows-x64", "linux-x64"]
wheels = [
    "./wheels/polychase_core-0.0.2-cp311-cp311-manylinux_2_28_x86_64.whl",
    "./wheels/polychase_core-0.0.2-cp311-cp311-win_amd64.whl",
    "./wheels/polychase_core-0.0.2-cp312-cp312-manylinux_2_28_x86_64.whl"
]

[dependencies]
scipy = ">=1.9.0"
pandas = ">=1.5.0"
numpy = ">=1.21.0"
opencv-contrib-python = ">=4.9.0.80"
python-dateutil = ">=2.8.2"
pytz = ">=2023.3"

[permissions]
files = "Write optical flow database to disk"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
  "lib/",
]
